export const DEFAULT_CANCEL_FEE = 1;
export const DEFAULT_CLOSE_FEE = 5;
export const DEFAULT_DISPUTE_TIME = 259200;
export const DEFAULT_PERCENTAGE_FOR_DISPUTE = 3;
export const DEFAULT_DRAFT_TIME = 86400;
export const DEFAULT_COUNCIL_AMOUNT = 25000000;
export const BODY_CHARACTERES_LIMIT = 65536;
export const BOUNTY_TITLE_LIMIT = 131;
export const MAX_TAGS = 3;
export const IM_AN_ADMIN = `I'm an admin`;
export const NOT_AN_ADMIN = `Not an admin`;
export const WANT_TO_CREATE_NETWORK = `I want to create a network`;
export const MISSING_ADMIN_SIGNATURE = `Missing admin signature`;
export const NOT_ADMIN_WALLET = `Wrong wallet`;
export const MISSING_CHAIN_ID = `Missing chain id`;
export const CHAIN_ID_NOT_SUPPORTED = `Given chain id is not supported`;
export const NO_NETWORKS_FOR_GIVEN_CHAIN_ID = `No networks for given chain id`;
export const CHAIN_NOT_CONFIGURED = `Chain not configured`;
export const WRONG_PARAM_URL = name => `Url ${name} was malformed`;
export const WRONG_PARAM_ADDRESS = name => `Address ${name} is malformed or 0 address`;
export const SEVEN_DAYS_IN_MS = 60 * 60 * 24 * 7 * 1000;
export const IM_AM_CREATOR_ISSUE = `I am the owner of this bounty`;
export const NOT_AN_CREATOR_ISSUE = `Not an creator issue`;
export const MISSING_CREATOR_ISSUE_SIGNATURE = `Missing creator issue signature`;