export const DEFAULT_CANCEL_FEE = 1;
export const DEFAULT_CLOSE_FEE = 5;
export const DEFAULT_DISPUTE_TIME = 259200;
export const DEFAULT_PERCENTAGE_FOR_DISPUTE = 3;
export const DEFAULT_DRAFT_TIME = 86400;
export const DEFAULT_COUNCIL_AMOUNT = 25000000;