export enum TransactionTypes {
  unknown = -1,
  createIssue,
  lock,
  unlock,
  approveTransactionalERC20Token,
  openIssue,
  delegateOracles,
  takeBackOracles,
  proposeMerge,
  dispute,
  closeIssue,
  redeemIssue,
  approveSettlerToken,
  recognizedAsFinish,
}
